# fly.toml app configuration file generated for queue-linaire on 2023-12-03T07:22:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "queue-linaire"
primary_region = "otp"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
